baseurl = "https://onigra.github.io"
languageCode = "ja"
hasCJKLanguage = "true"
enableRobotsTXT = "true"
title = "onigra.github.io"
theme = "Hucore"
copyright = "&copy; 2017 | <a href=\"https://twitter.com/onigra_\" target=\"_blank\">Onigra</a> | Powerd by <a href=\"https://github.com/mgjohansen/hucore\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> "
disqusShortname = "shortname"
googleAnalytics = "trackingcode"
enableEmoji = "true"

[permalinks]
post= "/blog/:year/:month/:day/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Yudai Suzuki"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/onigra"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/onigra_"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.menu]]
url = "/about/"
title = "About"

[[params.menu]]
url = "/post/"
title = "Archives"
